import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kay A. Lee - FFX Realty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <code className={styles.canary}>This Is Your New Home.</code>
        </h1>

        <p className={styles.description}>
          Contact Kay Agnes Lee of Fairfax Realty!
        </p>

        <p className={styles.description}>
          The design and development will be by Nick Baek and Daniel Lee of {' '}
          <code className={styles.code}>PRSNA Studio LLC</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Single Family Homes &rarr;</h2>
            <p>Click here to view listed single family homes.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Town Homes &rarr;</h2>
            <p>Click here to view listed town homes.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Condos &rarr;</h2>
            <p>Click here to view listed condominiums</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Property Management &rarr;</h2>
            <p>
              Click here to see property management services.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed, Developed, and Maintained by{' '}
          <span className={styles.logo}>
            <Image src="/PRSNA_Logo_Dark_Grey.svg" alt="PRSNA_studio Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
